name = "Vaje06"
uuid = "83613623-424b-4fd6-85bd-56b4df5d2115"
authors = ["Martin StariÄ <martin.staricc@gmail.com>"]
version = "0.1.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Weave = "44d3d7a6-8a23-5bf8-98c5-b353f8df5ec9"
