name = "Vaje05"
uuid = "9db4d513-688e-4ab7-b36e-7897030ad491"
authors = ["Martin StariÄ <martin.staricc@gmail.com>"]
version = "0.1.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Weave = "44d3d7a6-8a23-5bf8-98c5-b353f8df5ec9"
